### ISSUE TITLE
Empty string value error

### ISSUE THREAD

**Issue by machour** [diedsmiling/keys-diff#2]
### problem

It seems like keys with empty string values are considered absent from the object

### code

```
  const a = {
    foo: 'something',
    bar: 'something',
  };

  const b = {
    foo: 'something else',
    bar: '',
  };

  console.log(keysDiff(a, b));
```

### expected output

`[[], []]`

### actual output

`[[['bar']], []]`

**Comment by diedsmiling** [comment]
Thanks a lot for reporting! Fixed that one in #3
