### ISSUE TITLE
IE11 compatibility

### ISSUE THREAD

**Issue by bhagyas** [diedsmiling/keys-diff#5]
keys-diff does not work when a project is deployed on IE11.

**Comment by diedsmiling** [comment]
Hello!
Thanks for reporting. Can you please provide more information. Are there any errors? How can I reproduce it? How do you build your bundle?

Thanks!

**Comment by bhagyas** [comment]
The project which included keysDiff was built without arrow function polyfill,  but later got the keysDiff to work after copying the keysDiff code to the local project. I think adding a polyfill to the keysDiff would fix it. Or the code to be written without ES6 features.

**Comment by diedsmiling** [comment]
Got it, thanks. Will add a transpiler to the project.
